
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  adapter: postgresql
  database: toolsio_development
  encoding: unicode
  host: localhost
  pool: 5 

test:
  <<: *default
  database: toolsio_test
  encoding: unicode
  host: localhost
  pool: 5 

production:
  <<: *default
  database: toolsio_production
  username: timetracker
  password: <%= ENV['TIME_TRACKER_DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: 5
